package components;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 * This is the XOButton Object, a child of JButton.
 * Has images that the user sees.
 *
 */
public class XOButton extends JButton {

  /**
   * Auto generated by Eclipse
   */
  private static final long serialVersionUID = 1L;
  /**
   * The X icon that is displayed on buttons that player X has claimed
   */
  private final ImageIcon X_ICON = new ImageIcon(this.getClass().getResource("xicon.png"));
  /**
   * The O icon that is displayed on buttons that player O has claimed
   */
  private final ImageIcon O_ICON = new ImageIcon(this.getClass().getResource("oicon.png"));
  /**
   * Variable that keeps track of whether or not the button is filled
   */
  private boolean isFilled;

  /**
   * Constructor for XOButton
   * Makes it empty
   */
  public XOButton() {
  super();
  this.isFilled = false;
  }
  /**
   * Changes the icon to X, makes it 'filled'
   */
  public void setIconX()
  {
  setIcon(X_ICON);
  this.isFilled = true;
  }
  /**
   * Changes icon to O, makes it 'filled'
   */
  public void setIconO()
  {
  setIcon(O_ICON);
  this.isFilled = true;
  }
  /**
   * Changes icon to nothing, makes it 'empty'
   */
  public void setIconClear()
  {
  setIcon(null);
  this.isFilled = false;
  }
  /**
   * Checks to see if the Button is empty or not
   * @return true if the button belongs to X or O, false if it is empty
   */
  public boolean isFilled()
  {
  return this.isFilled;
  }
}//end class
