import java.awt.event.ActionEvent;

public abstract class AIBoard extends Board {

    /**
     * Auto-generated by Eclipse
     */
    private static final long serialVersionUID = 1L;
    protected int targetRow, targetCol;

    public AIBoard(Game game) {
        super(game);
        targetRow = -1;
        targetCol = -1;
        // TODO Auto-generated constructor stub
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        // TODO Auto-generated method stub
        XOButton obj = (XOButton)(e.getSource());
        int[] coords = this.getButtCoords(Integer.parseInt(e.getActionCommand()));
        if(!obj.isFilled()) {
            obj.setIconX();
            game.turn(1, coords[0], coords[1]);
        }else{
            return;
        }

    }

}
