import java.awt.event.ActionEvent;
/**
 * The easy board. The AI will just randomly place their pieces in empty cells.
 * 
 */
public class EasyBoard extends Board {

	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constructor for EasyBoard
	 * @param game the Game object that the board is contained in
	 */
	public EasyBoard(Game game)
	{
		super(game);
	}

	/**
	 * Logic for what happens when a button is pressed.
	 * Checks to see if the cell is empty, 
	 * places X there, 
	 * passes move to Game, 
	 * places O in a random empty cell on the board, 
	 * passes the move to Game.
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		XOButton obj = (XOButton)(e.getSource());
		int[] coords = this.getButtCoords(Integer.parseInt(e.getActionCommand()));
		if(!obj.isFilled()) {
			obj.setIconX();
			game.turn(1, coords[0], coords[1]);
		}else{
			return;
		}
    	boolean aiTookTurn = (game.isGameOver())? true:false;
    	int arow , acol;
    	while(!aiTookTurn){
    		arow = (int)(Math.random()*3); acol = (int)(Math.random()*3);
    		int i = (3*arow)+acol;
    		if(!butts[i].isFilled()){
    			butts[i].setIconO();
    			game.turn(2, arow, acol);
    			aiTookTurn = true;
    		}//end if
    	}//end while
	}//end act
}
