
public class HardBoard extends Board {

	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = -2959478284194737409L;

	public HardBoard(Game game)
	{
		super(game);
	}
}
